from enum import StrEnum


class Stage(StrEnum):
    NEW = "NEW"
    ANALYZING_SOURCE = "ANALYZING_SOURCE"
    RUNNING_CRF_ANALYSIS = "RUNNING_CRF_ANALYSIS"
    WAITING_FOR_ENCODE_SELECTION = "WAITING_FOR_ENCODE_SELECTION"
    ENCODING = "ENCODING"
    VALIDATING_ENCODE = "VALIDATING_ENCODE"
    WAITING_FOR_TRACK_SELECTION = "WAITING_FOR_TRACK_SELECTION"
    PREPARING_TRACKS = "PREPARING_TRACKS"
    REMUXING = "REMUXING"
    SCREENSHOT_CANDIDATE_GENERATION = "SCREENSHOT_CANDIDATE_GENERATION"
    SCREENSHOT_AGENT_SELECTION = "SCREENSHOT_AGENT_SELECTION"
    WAITING_FOR_SCREENSHOT_SELECTION = "WAITING_FOR_SCREENSHOT_SELECTION"
    SCREENSHOT_RENDERING = "SCREENSHOT_RENDERING"
    WAITING_FOR_RELEASE_DETAILS = "WAITING_FOR_RELEASE_DETAILS"
    GENERATING_RELEASE = "GENERATING_RELEASE"
    COMPLETE = "COMPLETE"
    ANALYZING_TRACKS = "ANALYZING_TRACKS"
    FINDING_SUBTITLES = "FINDING_SUBTITLES"
    REVIEWING_SUBTITLE_UPLOAD = "REVIEWING_SUBTITLE_UPLOAD"


STAGES = [
    stage
    for stage in Stage
    if stage not in (Stage.ANALYZING_TRACKS, Stage.FINDING_SUBTITLES, Stage.REVIEWING_SUBTITLE_UPLOAD)
]
TRACK_EDIT_STAGES = {
    Stage.RUNNING_CRF_ANALYSIS,
    Stage.WAITING_FOR_ENCODE_SELECTION,
    Stage.ENCODING,
    Stage.VALIDATING_ENCODE,
    Stage.WAITING_FOR_TRACK_SELECTION,
}
REMUX_STATES = {Stage.COMPLETE, Stage.WAITING_FOR_RELEASE_DETAILS, Stage.WAITING_FOR_SCREENSHOT_SELECTION}
# Keep scheduler eligibility and worker lease admission in agreement.
TRACK_TASK_STATES = {
    Stage.ANALYZING_TRACKS: TRACK_EDIT_STAGES,
    Stage.FINDING_SUBTITLES: TRACK_EDIT_STAGES | REMUX_STATES,
    Stage.REVIEWING_SUBTITLE_UPLOAD: TRACK_EDIT_STAGES | REMUX_STATES,
}
TASK_TYPES = {
    Stage.ANALYZING_SOURCE: "analyze",
    Stage.ANALYZING_TRACKS: "review_tracks",
    Stage.FINDING_SUBTITLES: "discover_subtitles",
    Stage.REVIEWING_SUBTITLE_UPLOAD: "review_uploaded_subtitle",
    Stage.PREPARING_TRACKS: "prepare_tracks",
    Stage.RUNNING_CRF_ANALYSIS: "crf_analysis",
    Stage.ENCODING: "encode",
    Stage.VALIDATING_ENCODE: "validate",
    Stage.REMUXING: "mux",
    Stage.SCREENSHOT_CANDIDATE_GENERATION: "generate_candidates",
    Stage.SCREENSHOT_AGENT_SELECTION: "select_screenshots",
    Stage.SCREENSHOT_RENDERING: "render_screenshots",
    Stage.GENERATING_RELEASE: "generate_release",
}
HUMAN_GATES = {
    Stage.WAITING_FOR_TRACK_SELECTION,
    Stage.WAITING_FOR_ENCODE_SELECTION,
    Stage.WAITING_FOR_SCREENSHOT_SELECTION,
    Stage.WAITING_FOR_RELEASE_DETAILS,
}


def next_stage(stage: str) -> Stage:
    index = STAGES.index(Stage(stage))
    if index == len(STAGES) - 1:
        raise ValueError("Job is already complete")
    return STAGES[index + 1]


def require_stage(actual: str, expected: Stage):
    if actual != expected:
        raise ValueError(f"Action requires {expected}; job is {actual}")
